services:
  postgres:
    image: postgres:15-alpine
    container_name: microlend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: microlend
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432"
    volumes:
      - microlend-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d microlend" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microlend-net

  daml-sandbox:
    build:
      context: .
      dockerfile: Dockerfile.daml-sandbox
    container_name: daml-sandbox
    ports:
      - "6865:6865"
    networks:
      - microlend-net

  daml-json-api:
    build:
      context: .
      dockerfile: Dockerfile.daml-json-api
    container_name: daml-json-api
    depends_on:
      daml-sandbox:
        condition: service_started
    environment:
      DAML_SANDBOX_HOST: daml-sandbox
      DAML_SANDBOX_PORT: 6865
    ports:
      - "7575:7575"
    networks:
      - microlend-net

volumes:
  microlend-postgres-data:


networks:
  microlend-net:
    #networks:
    #  auth-network:
    #    driver: bridge
